image: golang:1.13

stages:
  - build

build-linux-amd64:
  stage: build
  script:
    - cd ./bin
    - make

  artifacts:
    paths:
      - bin/blobber/blobber
      - bin/delegfetch/delegfetch
      - bin/sepdir/sepdir
